#!/bin/bash

set -eu

echo "Vagrant necesita poder ejecutar los siguientes comandos con privilegios de administrador (sudo) /usr/bin/sed y /usr/bin/tee"

plataforma="$(uname -s)"
extra_params=""
case "${plataforma}"
in
  Linux)
    extra_params="$extra_params --provider libvirt"
    echo Se usará libvirt como proveedor
    ;;
  Darwin)
    extra_params="$extra_params --provider virtualbox"
    echo Se usará VirtualBox como proveedor
    ;;
  *)
    echo "La plataforma ${plataforma} no está soportada"
    exit 1
    ;;
esac

vagrant up $extra_params && vagrant ssh -c "sudo su - ${USER}"
