#!/bin/bash

set -eu

vagrant_version="$(vagrant --version)"
echo "Requiere por lo menos Vagrant 1.8.1, versión encontrada: ${vagrant_version}"
echo "Vagrant necesita poder ejecutar los siguientes comandos con privilegios de administrador (sudo) /usr/bin/sed y /usr/bin/tee"
echo "Se requiere un servidor de NFS (Servidor de archivos/File server) funcionando e iniciado"

plataforma="$(uname -s)"
extra_params=""
case "${plataforma}"
in
  Linux)
    extra_params="$extra_params --provider libvirt"
    echo Se usará libvirt como proveedor
    if ! vagrant plugin list | grep libvirt > /dev/null
    then
      if which yum > /dev/null
      then
        sudo yum install libxslt-devel libxml2-devel libvirt-devel libguestfs-tools-c ruby-devel
      fi
      if which apt-get > /dev/null
      then
        sudo apt-get install libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
      fi
      vagrant plugin install vagrant-libvirt
    fi
    ;;
  Darwin)
    extra_params="$extra_params --provider virtualbox"
    echo Se usará VirtualBox como proveedor
    ;;
  *)
    echo "La plataforma ${plataforma} no está soportada"
    exit 1
    ;;
esac

vagrant up $extra_params && vagrant ssh -c "sudo su - ${USER}"
