#!/bin/bash

set -eu

# selinux permissive
setenforce permissive
sed -i.bak 's/^SELINUX=.*/SELINUX=permissive/' /etc/selinux/config

# crear al grupo y al usuario si no existen
if ! egrep "^${HOST_GROUP}:" /etc/group > /dev/null
then
  groupadd -f -g "${HOST_GID}" "${HOST_GROUP}"
fi
if ! egrep "^${HOST_USER}:" /etc/passwd > /dev/null
then
  extra_params=""
  if ls -l "${HOST_SHELL}" > /dev/null # si el shell del host existe lo ponemos
  then
    extra_params="${extra_params} -s ${HOST_SHELL}"
  fi
  if ! awk "$$3==\"${HOST_UID}\"{exit 1}" /etc/passwd > /dev/null # si uid del host no existe lo usamos
  then
    extra_params="${extra_params} -u ${HOST_UID}"
  fi
  useradd $extra_params -d "${HOST_HOME}" -g "${HOST_GID}" -G vagrant "${HOST_USER}"
fi

# instalar el paquete oasproj
oasproj_pkg="https://github.com/andresvia/oasproj/releases/download/v1.0.5/oasproj-1.0.5_travis.37-1.x86_64.rpm"
yum install -y "${oasproj_pkg}" || true
if ! rpm -q oasproj > /dev/null
then
  echo no se pudo instalar el paquete oasproj, sigue bajo tu propio riesgo
  exit 1
fi
